local Format = require 'color.format'

describe("clampXYY", function()
  it("clamps xyY values to normalized range [0, 1]", function()
    local x, y, Y = Format.clampXYY(0.5, 0.4, 0.8)
    assert.are.equal(0.5, x)
    assert.are.equal(0.4, y)
    assert.are.equal(0.8, Y)
  end)

  it("handles boundary values", function()
    local x1, y1, Y1 = Format.clampXYY(0, 0, 0)
    local x2, y2, Y2 = Format.clampXYY(1, 1, 1)
    assert.are.equal(0, x1)
    assert.are.equal(0, y1)
    assert.are.equal(0, Y1)
    assert.are.equal(1, x2)
    assert.are.equal(1, y2)
    assert.are.equal(1, Y2)
  end)

  it("clamps out-of-range values", function()
    local x, y, Y = Format.clampXYY(-0.1, 1.5, 0.5)
    assert.are.equal(0, x)
    assert.are.equal(1, y)
    assert.are.equal(0.5, Y)
  end)

  it("defaults Y to 1 when nil", function()
    local x, y, Y = Format.clampXYY(0.3, 0.6, nil)
    assert.are.equal(0.3, x)
    assert.are.equal(0.6, y)
    assert.are.equal(1, Y)
  end)

  it("clamps Y when provided", function()
    local x, y, Y = Format.clampXYY(0.3, 0.6, 1.2)
    assert.are.equal(0.3, x)
    assert.are.equal(0.6, y)
    assert.are.equal(1, Y)
  end)
end)