local cct_to_rgb = require 'color.cct_to_rgb'
local to_8bit = require 'color.to_8bit'

describe("cct_to_rgb", function()
  it("converts 3000K to correct RGB", function()
    local r, g, b = cct_to_rgb(3000)
    assert.is_true(r >= 0 and r <= 1)
    assert.is_true(g >= 0 and g <= 1)
    assert.is_true(b >= 0 and b <= 1)
    local r8, g8, b8 = to_8bit(r, g, b)
    assert.are.equal(255, r8)
    assert.are.equal(180, g8)
    assert.are.equal(108, b8)
  end)

  it("converts 10000K to correct RGB", function()
    local r, g, b = cct_to_rgb(10000)
    assert.is_true(r >= 0 and r <= 1)
    assert.is_true(g >= 0 and g <= 1)
    assert.is_true(b >= 0 and b <= 1)
    local r8, g8, b8 = to_8bit(r, g, b)
    assert.are.equal(204, r8)
    assert.are.equal(220, g8)
    assert.are.equal(255, b8)
  end)

  it("converts 1500K to correct RGB", function()
    local r, g, b = cct_to_rgb(1500)
    assert.is_true(r >= 0 and r <= 1)
    assert.is_true(g >= 0 and g <= 1)
    assert.is_true(b >= 0 and b <= 1)
    local r8, g8, b8 = to_8bit(r, g, b)
    assert.are.equal(255, r8)
    assert.are.equal(107, g8)
    assert.are.equal(0, b8)
  end)

  it("handles minimum CCT (1000K)", function()
    local r, g, b = cct_to_rgb(1000)
    assert.is_true(r >= 0 and r <= 1)
    assert.is_true(g >= 0 and g <= 1)
    assert.is_true(b >= 0 and b <= 1)
  end)

  it("handles maximum CCT (40000K)", function()
    local r, g, b = cct_to_rgb(40000)
    assert.is_true(r >= 0 and r <= 1)
    assert.is_true(g >= 0 and g <= 1)
    assert.is_true(b >= 0 and b <= 1)
  end)
end)