local hsv_to_xy = require 'color.hsv_to_xy'
local spec_helper = require 'spec.spec_helper'

describe("hsv_to_xy", function()
  it("converts HSV to xyY with valid ranges", function()
    local x, y, Y = hsv_to_xy(0.5, 0.5)
    assert.is_true(x >= 0 and x <= 1)
    assert.is_true(y >= 0 and y <= 1)
    assert.is_true(Y >= 0 and Y <= 1)
  end)

  it("handles valid HSV ranges", function()
    local x, y, Y = hsv_to_xy(0.5, 0.5)
    assert.is_true(x >= 0 and x <= 1)
    assert.is_true(y >= 0 and y <= 1)
    assert.is_true(Y >= 0 and Y <= 1)
  end)

  it("handles boundary HSV (0,0,0) - black produces NaN xy", function()
    local x, y, Y = hsv_to_xy(0, 0, 0)
    spec_helper.assert_is_nan(x, "x should be NaN for black")
    spec_helper.assert_is_nan(y, "y should be NaN for black")
    spec_helper.assert_near(Y, 0, 1e-6)
  end)

  it("handles boundary HSV (1,1,1)", function()
    local x, y, Y = hsv_to_xy(1, 1, 1)
    assert.is_true(x >= 0 and x <= 1)
    assert.is_true(y >= 0 and y <= 1)
    assert.is_true(Y >= 0 and Y <= 1)
  end)

  it("defaults v to 1.0 when omitted", function()
    local x1, y1, Y1 = hsv_to_xy(0.5, 0.5, 1.0)
    local x2, y2, Y2 = hsv_to_xy(0.5, 0.5)
    spec_helper.assert_near(x1, x2, 1e-10)
    spec_helper.assert_near(y1, y2, 1e-10)
    spec_helper.assert_near(Y1, Y2, 1e-10)
  end)
end)