local Color = {}

Color.rgb_to_cct = require 'color.rgb_to_cct'
Color.cct_to_rgb = require 'color.cct_to_rgb'
Color.xy_to_cct = require 'color.xy_to_cct'
Color.cct_to_xy = require 'color.cct_to_xy'
Color.xy_to_hsv = require 'color.xy_to_hsv'
Color.hsv_to_xy = require 'color.hsv_to_xy'
Color.cct_to_hsv = require 'color.cct_to_hsv'
Color.hsv_to_cct = require 'color.hsv_to_cct'
Color.rgb_to_hsv = require 'color.rgb_to_hsv'
Color.hsv_to_rgb = require 'color.hsv_to_rgb'
Color.rgb_to_xy = require 'color.rgb_to_xy'
Color.xy_to_rgb = require 'color.xy_to_rgb'
Color.rgb_to_hsl = require 'color.rgb_to_hsl'
Color.hsl_to_rgb = require 'color.hsl_to_rgb'
Color.scale = require 'color.scale'
Color.to_percentage = require 'color.to_percentage'
Color.from_percentage = require 'color.from_percentage'
Color.to_degrees = require 'color.to_degrees'
Color.from_degrees = require 'color.from_degrees'
Color.to_8bit = require 'color.to_8bit'
Color.from_8bit = require 'color.from_8bit'
Color.to_16bit = require 'color.to_16bit'
Color.from_16bit = require 'color.from_16bit'
Color.kelvin_to_mirek = require 'color.kelvin_to_mirek'
Color.mirek_to_kelvin = require 'color.mirek_to_kelvin'
Color.safe_hsv_to_xy = require 'color.safe_hsv_to_xy'
Color.safe_xy_to_hsv = require 'color.safe_xy_to_hsv'

return Color